In [1]:
import pandas as pd
import numpy as np

In [2]:
# make some virtual data and index
np.random.seed(0)

data = np.arange(5, 105, 5)
rn = np.random.randint(1, 5, data.size)
data = np.repeat(data, rn)

date_index = pd.DatetimeIndex(freq='D', start='20170202', periods=17)
date_index = pd.to_datetime(np.repeat(date_index, 3))

In [3]:
# example df
df = pd.DataFrame(data, index=date_index, columns=['data'])
df = df.reset_index()
df.head()

       index  data
0 2017-02-02     5
1 2017-02-02    10
2 2017-02-02    10
3 2017-02-03    10
4 2017-02-03    10

In [4]:
gdf = df.groupby(by=['index', 'data'])

In [5]:
gdf_keys = gdf.groups.keys()

In [6]:
for key in gdf_keys:
    subdf = gdf.get_group(key)
    # ...some code...
    print(subdf)
    print()

       index  data
0 2017-02-02     5

       index  data
1 2017-02-02    10
2 2017-02-02    10

       index  data
3 2017-02-03    10
4 2017-02-03    10

       index  data
5 2017-02-03    15

       index  data
6 2017-02-04    15

       index  data
7 2017-02-04    20

       index  data
8 2017-02-04    25

        index  data
9  2017-02-05    25
10 2017-02-05    25
11 2017-02-05    25

        index  data
12 2017-02-06    30
13 2017-02-06    30
14 2017-02-06    30

        index  data
15 2017-02-07    30

        index  data
16 2017-02-07    35
17 2017-02-07    35

        index  data
18 2017-02-08    35
19 2017-02-08    35

        index  data
20 2017-02-08    40

        index  data
21 2017-02-09    40
22 2017-02-09    40
23 2017-02-09    40

        index  data
24 2017-02-10    45
25 2017-02-10    45

        index  data
26 2017-02-10    50

        index  data
27 2017-02-11    50
28 2017-02-11    50
29 2017-02-11    50

        index  data
30 2017-02-12    55
31 2017-02-12    55

        index  data
32 2017-02-12    60

        index  data
33 2017-02-13    60
34 2017-02-13    60

        index  data
35 2017-02-13    65

        index  data
36 2017-02-14    70
37 2017-02-14    70
38 2017-02-14    70

        index  data
39 2017-02-15    70

        index  data
40 2017-02-15    75
41 2017-02-15    75

        index  data
42 2017-02-16    75

        index  data
43 2017-02-16    80

        index  data
44 2017-02-16    85

        index  data
45 2017-02-17    90

        index  data
46 2017-02-17    95
47 2017-02-17    95

        index  data
48 2017-02-18    95

        index  data
49 2017-02-18   100
50 2017-02-18   100